services:
  artnaxiapi:
    build:
      context: ./ArtNaxiApi
      dockerfile: Dockerfile
    ports:
    - "8080:80"
    - "8081:443"
    depends_on:
    - sqlserver
    - redis
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=https://+;http://+
    - ASPNETCORE_HTTPS_PORTS=8081
    - ASPNETCORE_Kestrel__Certificates__Default__Password=Test123!
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/artnaxiapi.pfx
    - STABLE_DIFFUSION_API_URL=http://host.docker.internal:7860/sdapi/v1/txt2img
    volumes:
    - avatarsvolume:/app/wwwroot/avatars
    - imagesvolume:/app/wwwroot/Images
    networks:
    - naxinetwork
    restart: on-failure
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Test123!"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - sqlvolume:/var/opt/mssql
    networks:
    - naxinetwork
  
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
    - naxinetwork

networks:
  naxinetwork:
    driver: bridge
  
volumes:
  sqlvolume:
  avatarsvolume:
  imagesvolume:
